---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# COMET

<!-- badges: start -->
<!-- badges: end -->

The goal of COMET is to simulate provide an open source framework to simulate the United States Lung Allocation System

## Installation

You can install the development version of COMET like so:

```{r, eval=FALSE}
# install.packages("devtools")
devtools::install_github("ClevelandClinicQHS/COMET")
```

## The rest to be added later

```{r example}
library(COMET)
## basic example code
## Simulates under LAS rules
r1 <- run_simulation(days = 400, can_start = 1000,
                     match_alg = match_las, wl_model = "LAS15", post_tx_model = "LAS15",
                     wl_weight = 2, post_tx_weight = 1, wl_cap = 365, post_tx_cap = 365, seed = 26638)

## Simulates the CAS rules
r2 <- run_simulation(days = 400, can_start = 1000,
                     match_alg = match_cas, wl_model = "CAS23", post_tx_model = "CAS23",
                     wl_weight = 0.25, post_tx_weight = 0.25, wl_cap = 365, post_tx_cap = 1825,
                     bio_weight = .15, pld_weight = 0.05, peds_weight = 0.2, efficiency_weight = 0.1, seed = 26638)

## You can mix and match systems, change weights
## for example simulate the LAS using the CAS models

## or maybe you want to test simualte what would happen if waitlist was weighted the same as post-transplatn under the LAS

## you can change the weights as well in the CAS, 

```

## A comparison of the models
```{r comparison of simualtions}
# eval_simulation()
# see how many were transplanted, donor count, waitlist deaths
eval_simulation(r1)

eval_simulation(r1, group = dx_grp)

```


## A further demonstration to show what is going on behind the scenes
```{r, eval = FALSE}
## One major advantage of the simulation is the use of synthetic candidates and donors
## All of these rely on bayesian hyperparametric distributions for the candidate and donor characteristics
syn_cands <- gen_and_spawn_candidates(days = 100)

syn_dons <- gen_and_spawn_donors(days = 10)
```

## 
```{r}
## screening
## Screening is done for height, blood type, organ count,
hm1 <- height_screen(syn_cands, syn_dons)
hm1
## returns if compabitible for single, double transplant, if a double transplant they will match for double lung
am1 <- abo_screen(syn_cands, syn_dons)
am1
## returns abo_exact abo compatible organs since that is a tie breaker in the LAS

## Ensure double with double, singles may take a double if only is assigned or either can
cm1 <- count_screen(syn_cands, syn_dons)
cm1

## Distance calculation 
lm1 <- las_dist_calc(syn_cands, syn_dons)
lm1

## ranking

lr1 <- calculate_las(syn_cands, wl_model = "LAS15", post_tx_model = "LAS15", wl_cap = 365, post_tx_cap = 365, wl_weight = 2, post_tx_weight = 1) |> dplyr::mutate(ov_rank = rank(-lu_score)) |> dplyr::arrange(ov_rank)

lr1

## matching and offering rank
las_offer_rank(hm1, am1, cm1, lm1, overall_ranking = lr1)
cas_offer_rank(hm1, am1, cm1, lm1, overall_ranking = lr1)

## calculating LAS/CAS scores
calculate_las(syn_cands, wl_model = "LAS15", post_tx_model = "LAS15", wl_cap = 365, post_tx_cap = 365, wl_weight = 2, post_tx_weight = 1)
calculate_sub_cas(syn_cands, wl_model = "LAS15", post_tx_model = "LAS15", wl_cap = 365, post_tx_cap = 365, wl_weight = 0.25,
                  post_tx_weight = 0.25, bio_weight = .15, peds_weight = .2, pld_weight = 0.05)

## One may know that CAS biological component is actually 3 of them. one for height, cpra, and blood type.
## Can instead specify these weights
calculate_sub_cas(syn_cands, wl_model = "LAS15", post_tx_model = "LAS15", wl_cap = 365, post_tx_cap = 365, wl_weight = 0.25,
                  post_tx_weight = 0.25, bio_weight = NA, peds_weight = .2, pld_weight = 0.05,
                  abo_weight = 0.10, height_weight = 0.05, cpra_weight = 0)

## updating patients
set.seed(266388)
update_patients(syn_cands, model = "CAS23", elapsed_time = days_on_waitlist, pre_tx = TRUE, cap = 365, date = 11)





## transplanting
# set.seed(367473)

mz <- match_las(syn_cands, syn_dons, wl_model = "LAS15", post_tx_model = "LAS15", 
                wl_cap = 365, post_tx_cap = 365, wl_weight = 2, post_tx_weight = 1)
mz

transplant_candidates(mz, rec_ids = NA, max_offer = NA)
## post-transplant
```


