# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mean Survival
#'
#' Calculates mean survival
#'
#' @param lp vector of linear predictors
#' @param surv_rates vector of survival times
#' @export
#'
#' @examples
#' lps <- c(0, 1, -.5)
#' surv_rates <- seq(1,.85, -.0005)
#' mean_survival(lps, surv_rates)
mean_survival <- function(lp, surv_rates) {
    .Call(`_COMET_mean_survival`, lp, surv_rates)
}

