# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sum loop C
#'
#' This function loops over the calculate mean survival
#'
#' @param x vector of linear predictors
#' @param y vector of survival times
#' @export
sum_loop_c <- function(x, y) {
    .Call(`_COMET_sum_loop_c`, x, y)
}

