# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Expected Survival
#'
#' Calculates Expected Survival Probability or Restricted Mean Survival Time (RMST)
#'
#' @param lp vector of linear predictors
#' @param surv_rate vector of survival times
#' @export
#'
#' @return if surv_rate is of length 1 returns probability of survival, if surv_rate is a vector resturns RMST
#'
#' @examples
#' lps <- c(0, 1, -.5)
#' ## Expected Survival
#' expected_survival(lps, 0.85)
#' ## Restricted Mean Survival Time
#' expected_survival(lps, seq(1,.85, -.0005))
expected_survival <- function(lp, surv_rate) {
    .Call(`_COMET_expected_survival`, lp, surv_rate)
}

