#' Synthetic Donor Set
#'
#' Similar data can be generated by  \code{gen_and_spawn_donors}
#' but this data was stored to keep examples and tests consistent.
#'
#' @format ## `syn_dons`
#' A tibble of 10 synthetic donors
#' \describe{
#' \item{d_id}{unqiue donor identifier}
#' \item{hospital}{integer from 1-1691 of donor hospital}
#' \item{recovery_day}{day of organ recovery}
#' \item{male}{sex male =1, female = 0}
#' \item{race_eth}{race and ethnicity of donor}
#' \item{hgt_in}{height in inches (nearest 0.5)}
#' \item{hgt_cm}{height in centimeters}
#' \item{cod}{cause of death}
#' \item{abo}{blood type}
#' \item{age}{age of donor}
#' \item{don_org}{donor organ}
#' \item{smoke_hist}{smoking history}
#' \item{gt_20pkyr}{greater than 20 pack years history}
#' \item{don_dcd}{deceased cardiac death}
#' \item{don_util}{donor able to be used for transplant(not transplanted outside US)}
#' \item{organs_avl}{1 or 2, number of lungs avilable}
#'
#' }
"syn_dons"
