#' Synthetic Candidate Set
#'
#' Similar data can be generated by \code{gen_and_spawn_candidates}
#' but this data was stored to keep examples.
#'
#' @format `syn_cands`  A tibble of 25 synethic candidates
#' \describe{
#' \item{c_id}{unique candidate identifier}
#' \item{center}{factor of 1-61 unique transplant center}
#'  \item{listing_day}{date of listing}
#'  \item{male}{1=male, 0=female}
#'  \item{dx_grp}{diagnosis group (A, B, C, D)}
#'  \item{race_eth}{race or ethnicity (NH White, NH Black, Hispanic,
#'    Asian, Amer. Ind, Hawaiian, Multi/Other)}
#'  \item{age_at_listing}{age in years (decimal equivalent of nearest 1/365)}
#'  \item{airway}{airway function value}
#'  \item{oxygen}{oxygen function value}
#'  \item{abo}{blood type (A, B, AB, O)}
#'  \item{hgt_in}{height in inches (nearest 0.5)}
#'  \item{hgt_cm}{height in centimeters}
#'  \item{wgt_kg}{weight in kilograms}
#'  \item{bmi}{body mass index}
#'  \item{resp_supp}{respiratory support cluster (1, 2, 3, 4)}
#'  \item{surg_type}{type of surgery required (D=Double, S=Single, E= Either)}
#'  \item{diab}{diabetes (1,0)}
#'  \item{fev1}{forced expiratory volume in the first second (\% predicted)}
#'  \item{fvc}{forced vital capacity (\% predicted)}
#'  \item{pco2}{\ifelse{html}{\out{pCO<sub>2</sub> (mmHg)}}{\eqn{\textrm{pCO}_{2}\textrm{ (mmHg)}}}}
#'  \item{pf}{\ifelse{html}{\out{pO<sub>2</sub>/FiO<sub>2</sub> ratio}}{\eqn{\textrm{pO}_{2}\textrm{/FiO}_{2}\textrm{ ratio}}}}
#'  \item{po2}{\ifelse{html}{\out{pO<sub>2</sub> (mmHg)}}{\eqn{\textrm{pO}_{2}\textrm{ (mmHg)}}}}
#'  \item{pap_mean}{mean pulmonary artery pressure (mmHg)}
#'  \item{o2_freq}{oxygen frequency (1=At Rest, 2=At Night, 3=While Exercising Only, 4=None)}
#'  \item{vent}{ventilator use (Bipap, CPAP, Mechanical, None)}
#'  \item{walk6m}{six minute walk distance (feet)}
#'  \item{o2}{supplemental oxygen (L/min)}
#'  \item{bili}{bilirubin (mg/dL)}
#'  \item{creat}{creatinine (mg/dL)}
#'  \item{pap_syst}{systolic pulmonary artery pressure (mmHg)}
#'  \item{ci}{cardiac index \ifelse{html}{\out{(L/min/m<sup>2</sup>)}}{\eqn{\textrm{L/min/m}^{2}}}}
#'  \item{funstat}{functional status (1=No assistance, 2=Some Assitance, 3=Total Assistance)}
#'  \item{ecmo}{ECMO (1,0)}
#'  \item{cvp}{central venous pressure (mmHg)}
#'  \item{pco2_15}{\ifelse{html}{\out{increase in pCO<sub>2</sub> by 15 percent (1,0)}}{\eqn{\textrm{increase in pCO}_{2}\textrm{ by 15 percent (1,0)}}}}
#'  \item{pra}{Panel Reactive Antibodies (0-1)}
#'  \item{pld}{prior living donor (1,0)}
#'  \item{creat_150}{creatinine increase by 150 percent (1,0)}
#'  \item{bili_50}{increase of biliruin by 50 percent (1,0)}
#'  \item{age}{current age}
#'  \item{hgt_cm1}{height to the nearest centimter}
#'  \item{o2rest}{supplemental oxygen received at rest (L/min if o2_freq is At Rest)}
#'  \item{cont_mech}{continuous mechanical ventilation (1 if vent=Mechanical, 0 Otherwise)}
#'  \item{dx}{diagnosis, specific diagnosis see \code{\link{calc_las}} for details}
#'  \item{pabo}{proprotion of incompatible blood type (0-1 UNOS calculated)}
#'  \item{phgt}{proportion of incompatible height range (0-1 UNOS calculated)}
#'  \item{pcpra}{proprotion of incompatible pra (0-1 UNOS calculated)}
#'  \item{days_on_waitlist}{how long the person has been waiting for a transplant (not generated by \code{\link{gen_and_spawn}})}
#'
#' }
"syn_cands"
